config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  resources :users do 
    resources :trips do 
    end
  end  

  get 'session/new' => 'sessions#new', as: 'log_in'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy', as: 'log_out'

  get 'profiles' => 'profiles#index'
  get 'profiles/edit' => 'profiles#edit', as: 'edit_profiles'

end

app/models/trip.rb
# There is too much logic in this model that does not belong here.
# There should be a TripImporter (or something similar) which does the
# hard work of transforming data from the outside into data that
# this system understands.

class Trip < ActiveRecord::Base

  belongs_to :user

  def self.new_trip(start_address, end_address)
    start_coordinates = address_coordinates(start_address)
    end_coordinates = address_coordinates(end_address)

    start_station = nearest_station(start_coordinates)
    end_station = nearest_station(end_coordinates)

    start_address_label = coordinates_address(start_coordinates)
    end_address_label = coordinates_address(end_coordinates)

    trip = trip_hash(start_station, end_station, start_address, end_address, start_coordinates, end_coordinates, start_address_label, end_address_label)

    self.create(trip)
  end

  def self.address_coordinates(address)
    Geocoder.coordinates(address)
  end

  def self.coordinates_address(coordinates)
    Geocoder.address(coordinates)
  end

  def self.nearest_station(address_coordinates)
    all_stations = Citibikenyc.branches["results"]
    station_array = []

    all_stations.each do |station|

      distance_from_address = Geocoder::Calculations.distance_between(address_coordinates, [(station['latitude']),(station['longitude'])])

      station_info = {
                      :station_id => (station['id']),
                      :label => (station['label']),
                      :latitude => (station['latitude']),
                      :longitude => (station['longitude']),
                      :distance => distance_from_address
                     }

      station_array << station_info
    end

    sorted = station_array.sort{ |x, y| x[:distance] <=> y[:distance] }

    sorted.each do |station|
      return station if station_state(station[:station_id]).fetch("status", "not active") == "Active" &&  station_state(station[:station_id]).fetch("availableBikes", 0).to_i > 0
    end

  end

  def self.trip_hash(start_station, end_station, start_address, end_address, start_coordinates, end_coordinates, start_address_label, end_address_label)
    {
     :start_station_id => start_station[:station_id],
     :start_station_label => start_station[:label],
     :start_station_latitude => start_station[:latitude],
     :start_station_longitude => start_station[:longitude],
     :end_station_id => end_station[:station_id],
     :end_station_label => end_station[:label],
     :end_station_latitude => end_station[:latitude],
     :end_station_longitude => end_station[:longitude],
     :start_address => start_address,
     :start_lat => start_coordinates[0],
     :start_long => start_coordinates[1],
     :end_address => end_address,
     :end_lat => end_coordinates[0],
     :end_long => end_coordinates[1],
     :start_address_label => start_address_label,
     :end_address_label => end_address_label
    }
  end

  def total_distance
    ( Geocoder::Calculations.distance_between([self.start_station_latitude, self.start_station_longitude], [self.start_lat, self.start_long]) +
     Geocoder::Calculations.distance_between([self.start_lat, self.start_long], [self.end_lat, self.end_long]) +
     Geocoder::Calculations.distance_between([self.end_lat, self.end_long], [self.end_station_latitude, self.end_station_longitude])
    ).round(2)
  end

  private

  def self.station_state(id)
    station_activity_arr = Citibikenyc.stations_status["results"]
    station_activity_arr.each do |station|
      return station if station.id == id
    end
    {status: "Not Active"}
  end

end




# in order to make this information valuable, it should be stored as a
# fixture / dataset for testing purposes.

# Citibikenyc.stations_status["results"]
# ___________________________
# [331] {
#                   "id" => 3002,
#               "status" => "Active",
#       "availableBikes" => 17,
#       "availableDocks" => 6
#   }


# bike_stations
# _____________
# {
#   :start => {
#     :station_id => 127,
#     :label => "One Court Square",
#     :latitude => 40.7467393577099,
#     :longitude => -73.9434874802828,
#     :distance => 0.5966593465631346
#     },
#     :end => {
#       :station_id => 228,
#       :label => "22 W. 32nd St",
#       :latitude => 40.7475128173828,
#       :longitude => -73.986946105957,
#       :distance => 0.09803588893167761
#     }
#   }

app/models/user.rb
class User < ActiveRecord::Base

  has_many :trips
  has_secure_password

  validates :email, presence: true, confirmation: true, uniqueness: true , email: true

  validates :password, length: {within: 8..14, too_short: "is too short, it needs to be between 8 and 14 characters", too_long: "is too long, it needs to be between 8 and 14 characters"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to log_in_path if current_user.nil?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to new_user_trip_path(:user_id => user.id), notice: "Signed In as #{user.email}"
    else
      redirect_to log_in_path, alert: "Log In Failed"
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to log_in_path, notice: "Logged Out"
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @trips = User.find(current_user).trips
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @trip = Trip.new(:user => @user)
  end

  def create

    if params[:current_address] == 'true'
      start_address = request.remote_ip
    else
      start_address = params.require(:trip).permit(:start_address)['start_address']
    end

    end_address = params.require(:trip).permit(:end_address)['end_address']

    trip = Trip.new_trip(start_address, end_address)

    current_user.trips << trip

    redirect_to user_trip_path(:id => trip.id)
  end

  def destroy
    Trip.delete(params[:id])
    redirect_to user_trips_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:edit, :update, :show] # huh??

  def index
    
    @user = current_user
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to log_in_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(current_user)
    if @user.update_attributes(user_params)
      redirect_to new_user_trip_path(current_user)
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :email_confirmation, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>peddlr</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Muli:300,400|Amaranth:400,700' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <div class="container">

      <%= yield %>

    </div>
  </body>
</html>

app/views/trips/index.html.erb
<h2>A list of your trips</h2>


<ol>
  <% @trips.each do |trip| %>
    <li>
      <h3><%= trip.start_address_label %></h3> to <h3><%= trip.end_address_label %></h3>

    </li>
    <ul>
      <li>
        <h4><%= trip.created_at.strftime("%-m/%-d/%Y") %></h4>
      </li>
      <ul>

        <li>
          End Station: <%= trip.end_station_label %>
        </li>
        <li>
          Total Distance: <%= trip.total_distance %> miles
        </li>
      </ul>
      <%= link_to "Trip Details", user_trip_path(:id => trip.id), class: 'button' %>
      <%= link_to "Delete Trip", user_trip_path(current_user, trip), method: :delete, class: 'button' %>
    </ul>
  <% end %>
</ol>

<%= link_to "Create Another Trip", new_user_trip_path(current_user), class: 'button' %>

app/views/trips/new.html.erb
<div class="welcome eight columns">
  <h2>Welcome <%= current_user.name %></h2>
  <h4>You are currently logged in as <%= current_user.email %></h4>



  <%= form_for [ @user, @trip ] do |f| %>
    <%= label_tag(:current_address_true, "Use Current Location") %>
    <%= radio_button_tag(:current_address, true) %>
    <%= f.label :start_address %>
    <%= f.text_field :start_address %>
    <%= f.label :end_address %>
    <%= f.text_field :end_address %>
    <%= f.submit %>
  <% end %>



  <p><%= link_to "Log Out", log_out_path, method: :delete, class: 'button' %></p>
  <p><%= link_to "View Your Profile", edit_user_path(current_user), class: 'button' %></p>
  <p><%= link_to "See Your Past Trips", user_trips_path(current_user), class: 'button' %></p>

</div>

<div class="eight columns">








</div>

app/views/trips/show.html.erb
<div class="sixteen columns">
  <h2>Here are your trip details</h2>

  <div class="eight columns">
    <ul>
      <li>
        <h4><%= @trip.start_address_label %> <br/><h5>to</h4><br/> <h4><%= @trip.end_address_label %></h4>
      </li>
      <li>
        Total Distance: <%= @trip.total_distance %> miles
      </li>
      <li>
        Nearest Citi Bike Station to Origin: <%= @trip.start_station_label%>
      </li>

      <li>
        Nearest Citi Bike Station to Destination: <%= @trip.end_station_label %>
      </li>
    </ul>
    <%= link_to "Create Another Trip", new_user_trip_path, class: 'button' %>
    <%= link_to "Your Trips", user_trips_path, class: 'button' %>
  </div>

  <!-- That looks scary and it should probably be in app/helpers/trip_helper.rb -->
  <img src="http://maps.googleapis.com/maps/api/staticmap?size=400x600&maptype=roadmap&path=color:blue%7Cweight:5%7C<%= @trip.start_lat.round(6) %>,<%= @trip.start_long.round(6) %>5%7C<%= @trip.start_station_latitude.round(6) %>,<%= @trip.start_station_longitude.round(6) %>&path=color:red%7Cweight:5%7C<%= @trip.start_station_latitude.round(6) %>,<%= @trip.start_station_longitude.round(6) %>%7C<%= @trip.end_station_latitude.round(6) %>,<%= @trip.end_station_longitude.round(6) %>&path=color:blue%7Cweight:5%7C<%= @trip.end_station_latitude.round(6) %>,<%= @trip.end_station_longitude.round(6) %>%7C<%= @trip.end_lat.round(6) %>,<%= @trip.end_long.round(6) %>&markers=color:blue%7C<%= @trip.start_lat.round(6) %>,<%= @trip.start_long.round(6) %>&markers=color:red%7C<%= @trip.start_station_latitude.round(6) %>,<%= @trip.start_station_longitude.round(6) %>&markers=color:red%7C<%= @trip.end_station_latitude.round(6) %>,<%= @trip.end_station_longitude.round(6) %>&markers=color:blue%7C<%= @trip.end_lat.round(6) %>,<%= @trip.end_long.round(6) %>&sensor=false" >





</div>

app/views/users/edit.html.erb
<h3>Edit Your Profile</h3>

<% if @user.errors.any? %>
  <div class="errors">
    <h5 class="error-count">
      The form has <%= pluralize(@user.errors.count, "error") %>.
    </h5>
    <ul class= "error-list">
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f. text_field :name %>
    <%= f.label :email %>
    <%= f. text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit %>
<% end %>

<%= link_to "Cancel", new_user_trip_path(current_user), class: 'button'%>

app/views/users/new.html.erb
<div class="sixteen columns header">
    <h1>peddlr</h1>
</div>



<div class="sixteen columns form">
    <%= form_for @user do |f| %>
        <%= f. text_field :name, :placeholder => "name" %>
        <%= f. text_field :email, :placeholder => "email" %>
        <%= f.text_field :email_confirmation, :placeholder => "email confirmation" %>
        <%= f.password_field :password, :placeholder => "password" %>
        <%= f.password_field :password_confirmation, :placeholder => "password confirmation" %>
        <%= f.submit "Create Account" %>
    <% end %>

    <%= link_to "Already have an account?", log_in_path, class: 'button' %>
</div>

<% if @user.errors.any? %>
    <div class="sixteen columns errors">
        <h4 class="error-count">
            The form has <%= pluralize(@user.errors.count, "error") %>.
        </h4>
        <ul class= "error-list">
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>        
    </div>
<% end %>